import "./globals.css";

import { cn } from "@app/client/lib/utils";

import Footer from "../components/global/footer";
import Navbar from "../components/global/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased")}>
        {children}
      </body>
    </html>
  );
}
